apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.deployment.app.image.containerPort }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-app