apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-redis
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
      role: master
      tier: backend
  replicas: {{ .Values.deployment.redis.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
        role: master
        tier: backend
    spec:
      containers:
        - name: redis
          image: {{ .Values.deployment.redis.image.name }}
          imagePullPolicy: {{ .Values.deployment.redis.image.imagePullPolicy }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: {{ .Values.deployment.redis.image.containerPort }}
