---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-redis
    role: master
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: {{ .Values.deployment.redis.image.containerPort }}
  selector:
    app: {{ .Release.Name }}-redis
    role: master
    tier: backend